### ISSUE TITLE
check out rec_to_nwb

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-conversion-tools#63]
Loren Frank's lab is doing something very similar to what we are doing [here](https://github.com/LorenFrankLab/rec_to_nwb). I don't think we need to adopt their yaml structure outright- this solution is very tailored to their specific form of data whereas ours is meant to be flexible across the different types of data supported by NWB. On the other hand, there are some structures in their yaml that I think we might want to adopt.

I like this section in particular:

```yaml
tasks:
   - task_name:          Sleep,
     task_description:   The animal sleeps in a small empty box.
     camera_id:
       - 0
     task_epochs:
       - 1
       - 3
       - 5
   - task_name:            Stem+Leaf,
     task_description:     Spatial Bandit,
     camera_id:
       - 1
     task_epochs:
       - 2
       - 4
```
